In [1]:
import numpy as np
from ase.build import bulk
from ase.visualize import view


In [2]:

# 构建铜晶体体系
cu = bulk("Cu", cubic=True)
print(cu.positions)
print(cu.cell)

[[0.    0.    0.   ]
 [0.    1.805 1.805]
 [1.805 0.    1.805]
 [1.805 1.805 0.   ]]
Cell([3.61, 3.61, 3.61])


In [3]:
# 获取当前的晶格矩阵
matrix = cu.get_cell()

# 在 x 方向上添加应变
matrix[0][0] *= 1.5

# 将新的晶格矩阵赋值给 原始 Cu 对象 
cu.set_cell(matrix)

# 输出 Cu 对象中的所有原子坐标
print(cu.positions)
print(cu.cell)

[[0.    0.    0.   ]
 [0.    1.805 1.805]
 [1.805 0.    1.805]
 [1.805 1.805 0.   ]]
Cell([5.415, 3.61, 3.61])


In [7]:
from ase.build import bulk

# 构建铜晶体体系
cu = bulk("Cu", cubic=True)

# 输出原始的晶格矩阵
print("原始晶格矩阵：")
print(cu.get_cell())
print(cu.positions)
# 在 x 方向上添加应变
matrix = cu.get_cell()
matrix[0][0] *= 1.5

# 将新的晶格矩阵赋值给 Cu 对象 
cu.set_cell(matrix, scale_atoms=True)

# 输出新的晶格矩阵
print("\n 新的晶格矩阵：" )
print(cu.get_cell())
print(cu.positions)

原始晶格矩阵：
Cell([3.61, 3.61, 3.61])
[[0.    0.    0.   ]
 [0.    1.805 1.805]
 [1.805 0.    1.805]
 [1.805 1.805 0.   ]]

 新的晶格矩阵：
Cell([5.415, 3.61, 3.61])
[[0.     0.     0.    ]
 [0.     1.805  1.805 ]
 [2.7075 0.     1.805 ]
 [2.7075 1.805  0.    ]]


In [5]:
from ase.constraints import FixConstraint

# 创建 FixConstraint 对象，将所有银原子在 z 方向上的运动限制为不可动
constraints = FixConstraint([False, False, True] * len(ag))

NameError: name 'ag' is not defined

In [1]:
import numpy as np

def replace_nan_with_max(matrix):
    """
    将矩阵中的 NaN 值替换为对应列的最大值
    
    Args：
        matrix: 要处理的二维列表，其中可能包含 NaN 值
        
    Returns:
        list: 返回处理后的二维列表
    """
    matrix = np.array(matrix) # 转换为 numpy 数组，以便使用 numpy 的函数
    max_values = np.nanmax(matrix, axis=0) # 按列计算最大值，忽略 NaN 值
    nan_mask = np.isnan(matrix) # 找出所有的 NaN 值
    matrix[nan_mask] = np.take(max_values, np.where(nan_mask)[1]) # 替换 NaN 值为对应列的最大值
    return matrix.tolist() # 转换回 Python 列表并返回


In [2]:
my_matrix = [
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, np.nan]
]

new_matrix = replace_nan_with_max(my_matrix)
print(new_matrix)


[[1.0, 2.0, 6.0], [4.0, 8.0, 6.0], [7.0, 8.0, 6.0]]


In [7]:
def my_func(num):
    if num < 0:
        raise ValueError("Num should be positive")
    return(num+1)

my_func(-1)  # 抛出 ValueError 异常



ValueError: Num should be positive